plugins {
    id "com.android.application"
}

android {
    namespace "com.techfun.basiccontrols.samples"
    compileSdk 35

    defaultConfig {
        applicationId "com.techfun.basiccontrols.samples"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation project(":basiccontrols")
}
