name: tech_skill_planet_basic_controls_example
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tech_skill_planet_basic_controls:
    path: ..

flutter:
  uses-material-design: true
