plugins {
    id "com.android.library"
}

android {
    namespace "com.techfun.basiccontrols"
    compileSdk 35

    defaultConfig {
        minSdk 23
        consumerProguardFiles "consumer-rules.pro"
    }

    sourceSets {
        main {
            assets.srcDirs = ["src/main/assets"]
        }
        debug {
            java.srcDirs = ["src/debug/java"]
        }
    }
}
