const THEMES = {
  sky: {
    key: 'sky',
    dark: false,
    pageStart: '#DDF4FF',
    pageEnd: '#F9FDFF',
    textPrimary: '#173A62',
    textSecondary: '#365D82',
    textTertiary: '#7895AE',
    surfaceRaised: '#FFFFFF',
    borderDefault: '#C8EAFF',
    brandPrimary: '#31A8FF',
    brandDark: '#1479D6',
    success: '#43CFC7',
    warning: '#FFD166',
    selectedFill: '#E8FDF7',
    activeFill: '#FFF7D7',
    danger: '#FF6B7A',
  },
  night: {
    key: 'night',
    dark: true,
    pageStart: '#0F1A2E',
    pageEnd: '#141E32',
    textPrimary: '#E8F4FF',
    textSecondary: '#B8D0E8',
    textTertiary: '#7A94B0',
    surfaceRaised: '#1E2D45',
    borderDefault: '#2A3F5C',
    brandPrimary: '#31A8FF',
    brandDark: '#1479D6',
    success: '#43CFC7',
    warning: '#FFD166',
    selectedFill: '#1E3A52',
    activeFill: '#3A3020',
    danger: '#FF6B7A',
  },
  mint: {
    key: 'mint',
    dark: false,
    pageStart: '#DFFAF2',
    pageEnd: '#F8FFFC',
    textPrimary: '#123F3A',
    textSecondary: '#2F6B63',
    textTertiary: '#6C938D',
    surfaceRaised: '#FFFFFF',
    borderDefault: '#BDEFE2',
    brandPrimary: '#20BFA9',
    brandDark: '#0C8F7E',
    success: '#35C58B',
    warning: '#FFD166',
    selectedFill: '#E6FFF4',
    activeFill: '#FFF7D7',
    danger: '#FF6B7A',
  },
  sunrise: {
    key: 'sunrise',
    dark: false,
    pageStart: '#FFE8D6',
    pageEnd: '#FFFDF8',
    textPrimary: '#4A2B1A',
    textSecondary: '#80523A',
    textTertiary: '#AA8068',
    surfaceRaised: '#FFFFFF',
    borderDefault: '#FFD1AD',
    brandPrimary: '#FF8A3D',
    brandDark: '#D85C12',
    success: '#43CFC7',
    warning: '#FFD166',
    selectedFill: '#FFF1E7',
    activeFill: '#FFF7D7',
    danger: '#E24C5C',
  },
  violet: {
    key: 'violet',
    dark: false,
    pageStart: '#ECE6FF',
    pageEnd: '#FAF8FF',
    textPrimary: '#35206A',
    textSecondary: '#5A4294',
    textTertiary: '#8E7BB8',
    surfaceRaised: '#FFFFFF',
    borderDefault: '#D5C7FF',
    brandPrimary: '#8B5CF6',
    brandDark: '#6D28D9',
    success: '#43CFC7',
    warning: '#FFD166',
    selectedFill: '#F3EEFF',
    activeFill: '#FFF7D7',
    danger: '#FF6B7A',
  },
  rose: {
    key: 'rose',
    dark: false,
    pageStart: '#FFE6F0',
    pageEnd: '#FFF8FB',
    textPrimary: '#5A1F3A',
    textSecondary: '#8A4566',
    textTertiary: '#B07A94',
    surfaceRaised: '#FFFFFF',
    borderDefault: '#FFC8DD',
    brandPrimary: '#FF6B9D',
    brandDark: '#E03E74',
    success: '#43CFC7',
    warning: '#FFD166',
    selectedFill: '#FFF0F6',
    activeFill: '#FFF7D7',
    danger: '#E24C5C',
  },
  ocean: {
    key: 'ocean',
    dark: false,
    pageStart: '#D9F2FF',
    pageEnd: '#F5FCFF',
    textPrimary: '#10395A',
    textSecondary: '#2F6287',
    textTertiary: '#6A8FAA',
    surfaceRaised: '#FFFFFF',
    borderDefault: '#B8E4FF',
    brandPrimary: '#2D9CDB',
    brandDark: '#1577B0',
    success: '#43CFC7',
    warning: '#FFD166',
    selectedFill: '#E8F7FF',
    activeFill: '#FFF7D7',
    danger: '#FF6B7A',
  },
  lemon: {
    key: 'lemon',
    dark: false,
    pageStart: '#FFF6CC',
    pageEnd: '#FFFEF5',
    textPrimary: '#4A3D00',
    textSecondary: '#75621A',
    textTertiary: '#A8944A',
    surfaceRaised: '#FFFFFF',
    borderDefault: '#F5E08A',
    brandPrimary: '#F5C518',
    brandDark: '#C89B00',
    success: '#43CFC7',
    warning: '#FFD166',
    selectedFill: '#FFFBE6',
    activeFill: '#FFF7D7',
    danger: '#FF6B7A',
  },
};

const COLOR_THEME_KEYS = ['sky', 'mint', 'sunrise', 'ocean', 'violet', 'rose', 'lemon'];

const COLOR_THEME_LABELS = {
  sky: '天空蓝',
  mint: '薄荷绿',
  sunrise: '暖阳橙',
  ocean: '海洋蓝',
  violet: '梦幻紫',
  rose: '甜心粉',
  lemon: '柠檬黄',
};

function getTheme(key) {
  return THEMES[key] || THEMES.sky;
}

function themeClass(key) {
  return getTheme(key).dark ? 'theme-night' : 'theme-sky';
}

function getColorThemeOptions() {
  return COLOR_THEME_KEYS.map((key) => ({
    key,
    label: COLOR_THEME_LABELS[key] || key,
    color: THEMES[key].brandPrimary,
    pageStart: THEMES[key].pageStart,
  }));
}

module.exports = {
  THEMES,
  COLOR_THEME_KEYS,
  COLOR_THEME_LABELS,
  getTheme,
  themeClass,
  getColorThemeOptions,
};
